---
- name: dependency provisioning
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
    - raw: sudo apt-get update
    - name: install python2
      raw: sudo apt-get -y install python-minimal

- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Install Required Packages
      apt:
        name: ['git', 'vim', 'jq', 'parted', 'e2fsprogs', 'python3', 'python3-pip', 'unzip']

- import_playbook: telegraf.yml
  when: deploy_type != "local" and influxdb_server != ""
- import_playbook: sshd.yml
  when: deploy_type != "local" and use_ssh_users
- import_playbook: firewall.yml
  when: deploy_type != "local"
- import_playbook: updates.yml
  when: deploy_type != "local"
- import_playbook: fail2ban.yml
  when: deploy_type != "local"
- import_playbook: logwatch.yml
  when: deploy_type != "local"
- import_playbook: postfix.yml
  when: deploy_type != "local"
#- import_playbook: geth.yml
- import_playbook: bitcoind.yml
#- import_playbook: gethtxscan.yml
- import_playbook: dotnetcore.yml
- import_playbook: nbxplorer.yml
- import_playbook: java.yml
- import_playbook: waves.yml
- import_playbook: wavescache.yml

