---
- name: firewall
  hosts: all
  become: yes
  become_user: root

  tasks:

    - name: Install UFW
      apt: name=ufw state=latest

    - name: Configure ufw defaults
      ufw: direction={{ item.direction }} policy={{ item.policy }}
      with_items:
        - { direction: 'incoming', policy: 'deny' }
        - { direction: 'outgoing', policy: 'allow' }
      notify:
        - restart ufw

    - name: firewall for ssh
      ufw:
        if: "{{item.if}}"
        direction: "{{item.direction}}"
        rule: "{{item.rule}}"
        port: "{{item.port}}"
        proto: "{{item.proto}}"
      with_items:
        - { if: "{{if_external}}", rule: 'limit', direction: 'in', port: '{{ ssh_port | default("22") }}', proto: 'tcp' }
      notify:
        - restart ufw

    - name: Enable ufw logging
      ufw: logging=on
      notify:
        - restart ufw

    - name: Enable ufw
      ufw: state=enabled

  handlers:

    - name: restart ufw
      service: name=ufw state=restarted
