---
- name: geth
  hosts: all
  become: yes
  become_user: root

  vars:
    version: 1.8.20
    commit: 24d727b6
    gethrelease: geth-linux-amd64-{{version}}-{{commit}}
  tasks:
    - name: firewall for geth 
      ufw:
        if: "{{item.if}}"
        direction: "{{item.direction}}"
        rule: "{{item.rule}}"
        port: "{{item.port}}"
        proto: "{{item.proto}}"
      with_items:
              - { if: "{{if_internal}}", rule: 'allow', direction: 'in', port: '8545', proto: 'tcp' }
              - { if: "{{if_internal}}", rule: 'allow', direction: 'in', port: '30303', proto: 'tcp' }
      notify:
        - restart ufw

    - name: ansible group
      group: 
        name: geth
        state: present

    - name: ansible user
      user:
        name: geth
        shell: /usr/sbin/nologin
        groups: geth
        system: yes
        state: present

    - name: download and install geth
      unarchive:
        src: https://gethstore.blob.core.windows.net/builds/{{ gethrelease }}.tar.gz
        dest: /home/geth/
        remote_src: yes
        creates: /home/geth/{{ gethrelease }}

    - name: copy geth binary
      copy:
        src: /home/geth/{{ gethrelease }}/geth 
        dest: /usr/local/bin/geth
        remote_src: yes
        owner: geth
        group: geth
        mode: 0755

    - name: copy geth.service
      template:
        src: templates/geth.service
        dest: /etc/systemd/system/geth.service

    - name: copy geth_defaults
      template:
        src: templates/geth_defaults.j2
        dest: /etc/default/geth

    - name: stop geth service
      service: 
        name: geth 
        state: stopped
        enabled: no

    - name: set .ethereum ownership
      file: 
        path: /home/geth/.ethereum
        owner: geth
        group: geth
        state: directory
        recurse: yes

#    - name: start geth service
#      service: 
#        name: geth 
#        state: started
#        enabled: yes

  handlers:

    - name: restart ufw
      service: name=ufw state=restarted

