---
- name: java
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: install openjdk 8
      apt: name={{item}} state=latest
      with_items:
        - openjdk-8-jdk
        - openjdk-8-jre
        - ca-certificates
