---
- name: logwatch
  hosts: all
  become: yes
  become_user: root

  tasks:

    - name: Install logwatch
      action: apt pkg=logwatch state=present

    - name: Make logwatch mail $logwatch_email daily
      action: lineinfile dest=/etc/cron.daily/00logwatch regexp="^/usr/sbin/logwatch" line="/usr/sbin/logwatch --output mail --mailto {{ admin_email }} --detail high" state=present create=yes
