---
- name: nbxplorer
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: ansible group
      group: 
        name: xchwallet
        state: present

    - name: ansible user
      user:
        name: xchwallet
        shell: /usr/sbin/nologin
        groups: xchwallet
        system: yes
        state: present

    # remove dir if is not git (because we used to deploy another way)
    - shell: if [[ -d "/opt/NBXplorer/" && ! -d "/opt/NBXplorer/.git" ]]; then rm /opt/NBXplorer -rf; fi
      args:
        executable: /bin/bash

    - name: git clone/checkout nbxplorer
      git:
        repo: https://github.com/dgarage/NBXplorer.git
        dest: /opt/NBXplorer
        version: v2.0.0.55

    - file:
        path: /opt/NBXplorer
        owner: xchwallet
        group: xchwallet
        mode: 0755
        recurse: yes

    - file:
        path: /home/xchwallet/.nbxplorer/Main
        state: directory
        owner: xchwallet
        group: xchwallet
        mode: 0755

    - name: copy nbxplorer settings
      template:
        src: templates/nbxplorer_settings.config
        dest: /home/xchwallet/.nbxplorer/Main/settings.config

    - name: copy nbxplorer.service
      template:
        src: templates/nbxplorer.service
        dest: /etc/systemd/system/nbxplorer.service

    - name: stop nbxplorer service
      service: 
        name: nbxplorer
        state: stopped
        enabled: no

    - name: start nbxplorer service
      service: 
        name: nbxplorer
        state: started
        enabled: yes
