---
- name: nbxplorer
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: firewall for nbxplorer
      ufw:
        if: "{{item.if}}"
        direction: "{{item.direction}}"
        rule: "{{item.rule}}"
        port: "{{item.port}}"
        proto: "{{item.proto}}"
      with_items:
        - { if: "{{if_internal}}", rule: 'allow', direction: 'in', port: '24444', proto: 'tcp' }
      notify:
        - restart ufw

    - name: ansible group
      group: 
        name: xchwallet
        state: present

    - name: ansible user
      user:
        name: xchwallet
        shell: /usr/sbin/nologin
        groups: geth
        system: yes
        state: present

    - name: copy nbxplorer
      copy:
        src: ../NBXplorer/
        dest: /opt/NBXplorer
        owner: xchwallet
        group: xchwallet
        mode: 0755

    - file:
        path: /home/xchwallet/.nbxplorer/Main
        state: directory
        owner: xchwallet
        group: xchwallet
        mode: 0755

    - name: copy nbxplorer settings
      template:
        src: templates/nbxplorer_settings.config
        dest: /home/xchwallet/.nbxplorer/Main/settings.config

    - name: copy nbxplorer.service
      template:
        src: templates/nbxplorer.service
        dest: /etc/systemd/system/nbxplorer.service

    - name: stop nbxplorer service
      service: 
        name: nbxplorer
        state: stopped
        enabled: no

    - name: start nbxplorer service
      service: 
        name: nbxplorer
        state: started
        enabled: yes

  handlers:

    - name: restart ufw
      service: name=ufw state=restarted

