// <auto-generated />
using System;
using System.Numerics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using xchwallet;

namespace xchwallet.Migrations.FiatWallet
{
    [DbContext(typeof(FiatWalletContext))]
    [Migration("20190213021008_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("xchwallet.BankTx", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Amount");

                    b.Property<string>("BankMetadata");

                    b.Property<long>("Date");

                    b.HasKey("Id");

                    b.ToTable("BankTxs");
                });

            modelBuilder.Entity("xchwallet.ChainTx", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<BigInteger>("Amount")
                        .HasColumnType("string");

                    b.Property<long>("Confirmations");

                    b.Property<long>("Date");

                    b.Property<BigInteger>("Fee")
                        .HasColumnType("string");

                    b.Property<string>("From");

                    b.Property<long>("Height");

                    b.Property<string>("To");

                    b.Property<string>("TxId");

                    b.HasKey("Id");

                    b.ToTable("ChainTx");
                });

            modelBuilder.Entity("xchwallet.FiatWalletTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Tag");

                    b.HasKey("Id");

                    b.ToTable("WalletTags");
                });

            modelBuilder.Entity("xchwallet.FiatWalletTx", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccountName");

                    b.Property<string>("AccountNumber");

                    b.Property<long>("Amount");

                    b.Property<string>("BankAddress");

                    b.Property<string>("BankName");

                    b.Property<int?>("BankTxId");

                    b.Property<long>("Date");

                    b.Property<string>("DepositCode");

                    b.Property<int>("Direction");

                    b.Property<int>("FiatWalletTagId");

                    b.HasKey("Id");

                    b.HasIndex("BankTxId");

                    b.HasIndex("DepositCode")
                        .IsUnique();

                    b.HasIndex("FiatWalletTagId");

                    b.ToTable("WalletTxs");
                });

            modelBuilder.Entity("xchwallet.WalletAddr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Path");

                    b.Property<int>("PathIndex");

                    b.Property<int>("TagId");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("WalletAddr");
                });

            modelBuilder.Entity("xchwallet.WalletCfg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("WalletCfgs");
                });

            modelBuilder.Entity("xchwallet.WalletTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Tag");

                    b.HasKey("Id");

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.ToTable("WalletTag");
                });

            modelBuilder.Entity("xchwallet.WalletTx", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Acknowledged");

                    b.Property<int>("ChainTxId");

                    b.Property<int>("Direction");

                    b.Property<string>("Note");

                    b.Property<string>("TagOnBehalfOf");

                    b.Property<int>("WalletAddrId");

                    b.Property<long>("WalletId");

                    b.HasKey("Id");

                    b.HasIndex("ChainTxId");

                    b.HasIndex("WalletAddrId");

                    b.ToTable("WalletTx");
                });

            modelBuilder.Entity("xchwallet.FiatWalletTx", b =>
                {
                    b.HasOne("xchwallet.BankTx", "BankTx")
                        .WithMany()
                        .HasForeignKey("BankTxId");

                    b.HasOne("xchwallet.FiatWalletTag", "Tag")
                        .WithMany("Txs")
                        .HasForeignKey("FiatWalletTagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("xchwallet.WalletAddr", b =>
                {
                    b.HasOne("xchwallet.WalletTag", "Tag")
                        .WithMany("Addrs")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("xchwallet.WalletTx", b =>
                {
                    b.HasOne("xchwallet.ChainTx", "ChainTx")
                        .WithMany()
                        .HasForeignKey("ChainTxId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("xchwallet.WalletAddr", "Address")
                        .WithMany("Txs")
                        .HasForeignKey("WalletAddrId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
